// ─── Color Tokens ────────────────────────────────────────────────────────────
export const T = {
  bg:           '#0F0F0F',
  surface:      '#161616',
  surfaceRaised:'#1E1E1E',
  border:       '#2A2A2A',
  borderLight:  '#333333',
  text:         '#E8E0D4',
  textMuted:    '#888480',
  textFaint:    '#4A4845',
  accent:       '#C9A96E',
  accentDim:    '#7A6240',
  danger:       '#E05C5C',
  dangerDim:    '#6B2A2A',
  success:      '#5CB88A',
  necessary:    '#C9A96E',
  unnecessary:  '#E05C5C',
  type:         '#7B8DE0',
  typeDim:      '#7B8DE022',
};

// ─── Shared Style Objects ─────────────────────────────────────────────────────
export const css = {
  // Layout
  app: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: T.bg,
    color: T.text,
    fontFamily: "'Inter', -apple-system, sans-serif",
    fontSize: '14px',
  },

  // Sidebar
  sidebar: {
    width: '220px',
    minWidth: '220px',
    backgroundColor: T.surface,
    borderRight: `1px solid ${T.border}`,
    display: 'flex',
    flexDirection: 'column',
    position: 'sticky',
    top: 0,
    height: '100vh',
    overflow: 'hidden',
  },
  sidebarHeader: {
    padding: '24px 20px 20px',
    borderBottom: `1px solid ${T.border}`,
  },
  logo: {
    fontFamily: "'DM Mono', monospace",
    fontSize: '15px',
    fontWeight: '500',
    color: T.accent,
    letterSpacing: '0.05em',
  },
  logoSub: {
    fontSize: '11px',
    color: T.textMuted,
    marginTop: '2px',
    letterSpacing: '0.03em',
  },
  navSection: { padding: '16px 12px 8px' },
  navLabel: {
    fontSize: '10px',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: T.textFaint,
    padding: '0 8px',
    marginBottom: '6px',
  },
  navItem: (active) => ({
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 10px',
    borderRadius: '6px',
    cursor: 'pointer',
    backgroundColor: active ? T.surfaceRaised : 'transparent',
    color: active ? T.text : T.textMuted,
    fontSize: '13px',
    fontWeight: active ? '500' : '400',
    transition: 'all 0.15s',
    border: active ? `1px solid ${T.border}` : '1px solid transparent',
    marginBottom: '2px',
  }),
  sidebarFooter: {
    marginTop: 'auto',
    padding: '16px 12px',
    borderTop: `1px solid ${T.border}`,
  },
  userChip: { display: 'flex', alignItems: 'center', gap: '10px', padding: '8px 10px' },
  userAvatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    backgroundColor: T.accentDim,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    color: T.accent,
    fontWeight: '600',
    fontFamily: "'DM Mono', monospace",
  },

  // Main area
  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  topbar: {
    padding: '20px 28px',
    borderBottom: `1px solid ${T.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: T.surface,
  },
  pageTitle:    { fontSize: '16px', fontWeight: '600', color: T.text },
  pageSubtitle: { fontSize: '12px', color: T.textMuted, marginTop: '1px' },
  content:      { flex: 1, padding: '24px 28px', overflowY: 'auto' },

  // Cards
  summaryCard: {
    backgroundColor: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: '10px',
    padding: '24px 28px',
    marginBottom: '20px',
  },
  statCard: {
    backgroundColor: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: '8px',
    padding: '16px 18px',
  },
  statValue: {
    fontFamily: "'DM Mono', monospace",
    fontSize: '20px',
    color: T.text,
    fontWeight: '400',
  },
  statLabel: { fontSize: '11px', color: T.textMuted, marginTop: '4px' },

  // Typography
  bigNumber: {
    fontFamily: "'DM Mono', monospace",
    fontSize: '42px',
    fontWeight: '400',
    color: T.accent,
    lineHeight: '1',
    letterSpacing: '-0.02em',
  },
  bigNumberLabel: {
    fontSize: '11px',
    color: T.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    marginBottom: '8px',
  },

  // Split bar
  splitBar: {
    height: '4px',
    borderRadius: '2px',
    backgroundColor: T.border,
    marginTop: '16px',
    overflow: 'hidden',
    display: 'flex',
  },
  splitLabels: { display: 'flex', justifyContent: 'space-between', marginTop: '8px' },
  splitLabel: (color) => ({
    fontSize: '11px',
    color,
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  }),

  // Layout helpers
  grid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', marginBottom: '20px' },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '14px',
  },
  sectionTitle: {
    fontSize: '13px',
    fontWeight: '600',
    color: T.text,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },

  // Buttons
  btnPrimary: {
    backgroundColor: T.accent,
    color: '#0F0F0F',
    padding: '8px 16px',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '600',
    transition: 'all 0.15s',
  },
  btnGhost: {
    backgroundColor: 'transparent',
    color: T.textMuted,
    padding: '6px 10px',
    borderRadius: '5px',
    border: `1px solid ${T.border}`,
    cursor: 'pointer',
    fontSize: '11px',
    transition: 'all 0.15s',
  },
  btnDanger: {
    backgroundColor: T.dangerDim,
    color: T.danger,
    padding: '6px 10px',
    borderRadius: '5px',
    border: `1px solid ${T.dangerDim}`,
    cursor: 'pointer',
    fontSize: '11px',
  },

  // Expense card
  expenseCard: {
    backgroundColor: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: '8px',
    padding: '14px 18px',
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    transition: 'border-color 0.15s',
  },
  expenseLeft:  { flex: 1, minWidth: 0 },
  expenseDesc: {
    fontSize: '13px',
    fontWeight: '500',
    color: T.text,
    marginBottom: '4px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  expenseMeta: { display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' },
  expenseRight: { textAlign: 'right', flexShrink: 0 },

  // Chip
  chip: (bg, color) => ({
    fontSize: '10px',
    padding: '2px 7px',
    borderRadius: '3px',
    backgroundColor: bg,
    color: color,
    letterSpacing: '0.04em',
    fontWeight: '500',
  }),
  badge: (color) => ({
    display: 'inline-block',
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: color,
    flexShrink: 0,
  }),

  // Modal
  modal: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalBox: {
    backgroundColor: T.surface,
    border: `1px solid ${T.border}`,
    borderRadius: '10px',
    padding: '28px',
    width: '100%',
    maxWidth: '480px',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  modalTitle: { fontSize: '15px', fontWeight: '600', color: T.text, marginBottom: '20px' },

  // Form
  formRow:    { marginBottom: '14px' },
  formActions: { display: 'flex', gap: '10px', justifyContent: 'flex-end', marginTop: '20px' },
  label: {
    display: 'block',
    fontSize: '11px',
    color: T.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '9px 12px',
    backgroundColor: T.surfaceRaised,
    border: `1px solid ${T.border}`,
    borderRadius: '6px',
    color: T.text,
    fontSize: '13px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  select: {
    width: '100%',
    padding: '9px 12px',
    backgroundColor: T.surfaceRaised,
    border: `1px solid ${T.border}`,
    borderRadius: '6px',
    color: T.text,
    fontSize: '13px',
    outline: 'none',
    boxSizing: 'border-box',
    cursor: 'pointer',
  },

  // Tabs
  tabBar: {
    display: 'flex',
    gap: '4px',
    marginBottom: '20px',
    borderBottom: `1px solid ${T.border}`,
  },
  tab: (active) => ({
    padding: '8px 16px',
    fontSize: '12px',
    fontWeight: '500',
    color: active ? T.accent : T.textMuted,
    cursor: 'pointer',
    borderBottom: active ? `2px solid ${T.accent}` : '2px solid transparent',
    marginBottom: '-1px',
    transition: 'all 0.15s',
    background: 'none',
    border: 'none',
    borderBottom: active ? `2px solid ${T.accent}` : '2px solid transparent',
  }),

  // Empty state
  emptyState:      { textAlign: 'center', padding: '48px 20px', color: T.textMuted },
  emptyStateTitle: { fontSize: '14px', color: T.textMuted, marginBottom: '6px' },
  emptyStateHint:  { fontSize: '12px', color: T.textFaint },

  // Misc
  reconEntry: {
    backgroundColor: T.bg,
    border: `1px solid ${T.border}`,
    borderRadius: '6px',
    padding: '10px 14px',
    marginBottom: '8px',
  },
  hr: { border: 'none', borderTop: `1px solid ${T.border}`, margin: '16px 0' },
};
